name: Update Summaries

on:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository main branch
      uses: actions/checkout@v4
      with:
        ref: main
        fetch-depth: 0  # Include the full history and all branches
    - name: Set up python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip'
    - name: Install python requirements
      run: pip install -r scripts/requirements.txt
    - name: Run script
      run: python scripts/update_summaries.py
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Update readme"
